# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 203e8f77a8cc28fc920ffaaa030130c39593f6893b35e30e62a20f7f1466cfbb31f955e932927594b42065e40aba9cda262b449b126e5a5b564b908e80db8ca2

test:
  secret_key_base: 2dc7def1fd377431299d64b7d5b79cbc9d9d2ead7d54a81339392be36f12d2d4135a8f169795c1c051cb35c9ac430012e85573cd88f90b350ed99e919183b767

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
